In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_wine

In [3]:
data=load_wine()

In [4]:
x=pd.DataFrame(data.data,columns=data.feature_names)

In [5]:
x

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [6]:
y=data.target

In [7]:
data.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [15]:
y_pred=model.predict(x_test)

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
accuracy_score(y_test,y_pred)

1.0

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [20]:
y_pred=model.predict(x_test)

In [21]:
y_pred

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 2, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 0, 1, 0, 0, 1, 2, 0, 0, 0])

In [22]:
accuracy_score(y_test,y_pred)

0.9444444444444444

In [23]:
from sklearn.svm import SVC

In [24]:
model=SVC()
model.fit(x_train,y_train)

SVC()

In [25]:
y_pred=model.predict(x_test)

In [26]:
accuracy_score(y_test,y_pred)

1.0

In [27]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [28]:
y_pred=model.predict(x_test)

In [29]:
accuracy_score(y_test,y_pred)

1.0

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [32]:
y_pred=model.predict(x_test)

In [33]:
accuracy_score(y_test,y_pred)

0.9444444444444444

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
model=RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [36]:
y_pred=model.predict(x_test)

In [39]:
accuracy_score(y_test,y_pred)

1.0

In [40]:
df=sns.load_dataset("titanic")

In [41]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [42]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [43]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [45]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [46]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [47]:
df.drop(['embark_town','deck'],axis=1,inplace=True)

In [48]:
df['age'].fillna(df['age'].mean(),inplace=True)

C:\Users\Kavyashree N\AppData\Local\Temp\ipykernel_15868\1492264711.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace=True)

In [49]:
df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)

C:\Users\Kavyashree N\AppData\Local\Temp\ipykernel_15868\1024298632.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)

In [50]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age           0
sibsp         0
parch         0
fare          0
embarked      0
class         0
who           0
adult_male    0
alive         0
alone         0
dtype: int64

In [51]:
from sklearn.preprocessing import LabelEncoder

In [52]:
le=LabelEncoder()
df['sex']=le.fit_transform(df['sex'])

In [53]:
df['sex']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: sex, Length: 891, dtype: int32

In [54]:
df['embarked']=le.fit_transform(df['embarked'])

In [55]:
df.drop(['who','alive'],axis=1,inplace=True)

In [56]:
df.drop(['class'],axis=1,inplace=True)

In [57]:
x=df.drop('survived',axis=1)

In [58]:
y=df['survived']

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [61]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.preprocessing import StandardScaler

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    891 non-null    int64
 1   pclass      891 non-null    int64
 2   sex         891 non-null    int32
 3   age         891 non-null    float64
 4   sibsp       891 non-null    int64
 5   parch       891 non-null    int64
 6   fare        891 non-null    float64
 7   embarked    891 non-null    int32
 8   adult_male  891 non-null    bool
 9   alone       891 non-null    bool
dtypes: bool(2), float64(2), int32(2), int64(4)
memory usage: 50.6 KB

In [63]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [64]:
from sklearn.linear_model import LogisticRegression

In [65]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [67]:
y_pred=model.predict(x_test)

In [68]:
accuracy_score(y_test,y_pred)

0.8156424581005587

In [69]:
from sklearn.neighbors import KNeighborsClassifier

In [71]:
model=KNeighborsClassifier()
model.fit(x_train,y_train)

KNeighborsClassifier()

In [72]:
y_pred=model.predict(x_test)

In [73]:
accuracy_score(y_test,y_pred)

0.8156424581005587

In [74]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC()

In [75]:
y_pred=model.predict(x_test)

In [76]:
accuracy_score(y_test,y_pred)

0.8156424581005587

In [77]:
from sklearn.naive_bayes import GaussianNB

In [78]:
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [79]:
y_pred=model.predict(x_test)

In [80]:
accuracy_score(y_test,y_pred)

0.7877094972067039

In [89]:
from sklearn.tree import DecisionTreeClassifier

In [90]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [91]:
y_pred=model.predict(x_test)

In [92]:
accuracy_score(y_test,y_pred)

0.7541899441340782

In [93]:
from sklearn.ensemble import RandomForestClassifier

In [94]:
model=RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [95]:
y_pred=model.predict(x_test)

In [96]:
accuracy_score(y_test,y_pred)

0.8268156424581006

In [97]:
from sklearn.datasets import load_iris

In [98]:
data=load_iris()

In [99]:
x=data.data

In [100]:
y=data.target

In [101]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [102]:
model=RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [103]:
y_pred=model.predict(x_test)

In [104]:
accuracy_score(y_test,y_pred)

1.0

In [105]:
## to save model

In [106]:
import pickle

In [107]:
with open("iris_model_sample.pkl","wb") as file:
    pickle.dump(model,file)

In [ ]:
Assignment:
iris---deployement(streamlit)
breast_cancer
wine
titanic